name: Publish to npm

on:
  workflow_dispatch:
    inputs:

      features:
        type: text
        description: changelog features

      bugfixes:
        type: text
        description: changelog bugfixes

      breaking-changes:
        type: text
        description: changelog breaking changes
        
      version:
        type: choice
        description: Choose which version to release
        options:
        - beta
        - patch
        - minore
        - majore

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
        
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."

    
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: CHECK
        run: echo "${{ github.event.inputs.version }}"

      - name: Install dependencies
        run: yarn

      - name: Build app
        if: ${{ github.event.inputs.version }} === 'beta'
        run: yarn build

      - name: Set NPM Token
        if: ${{ github.event.inputs.version }} === 'beta'
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
        
      - name: Set current commit sha
        if: ${{ github.event.inputs.version }} === 'beta'
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get current released version
        if: ${{ github.event.inputs.version }} === 'beta'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Publish
        if: ${{ github.event.inputs.version }} === 'beta'
        run: npm run pub:beta
        env:
          BETA_VERSION: ${{ steps.package-version.outputs.current-version}}-beta.${{ steps.vars.outputs.sha_short }}
