name: Publish to npm

on:
  workflow_dispatch:
    inputs:

      features:
        type: text
        description: changelog features

      bugfixes:
        type: text
        description: changelog bugfixes

      breaking-changes:
        type: text
        description: changelog breaking changes
        
      choice:
        type: choice
        description: Выбери какая версия будет выпускаться
        options:
        - beta
        - patch
        - minore
        - majore
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: yarn test

  publish-npm:
    needs: [build, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
